services:
  - docker

script:
  - docker-compose -f docker/docker-compose.yml build
  - docker run -it drugilsberg/depiction python3 -m unittest discover -t . -p "*_test.py" depiction

deploy:
  provider: script
  skip_cleanup: true
  script: sh .travis/deploy.sh
  on: 
    branches:
      only:
        - master
