services:
  - docker

script:
  - docker-compose -f docker/docker-compose.yml build
  - docker-compose -f .travis/docker-compose.yml up -d
  - docker exec -it depiction-test bash -c 'python3 -m unittest discover -t /build/ -p "*_test.py" depiction; (exit $?)'
  - echo $?

deploy:
  provider: script
  skip_cleanup: true
  script: sh .travis/deploy.sh
  on: 
    branches:
      only:
        - master
