name: depiction-env
channels:
  - https://conda.anaconda.org/rdkit
dependencies:
  - rdkit=2019.03.1
  - python>=3.6
  - pip
  - pip:
    - spacy==2.1.4
    - pandas==0.24.2
    - scikit-learn==0.21.2
    - tensorflow==1.14.0
    - torch==1.0.0
    - seaborn==0.9.0
    - lime==0.1.1.32
